"use client";
import { CTOutputs } from "@/lib/computations/ct";
import { PTOutputs } from "@/lib/computations/pt";

interface PrintButtonProps {
  type: "CT" | "PT";
  inputs: Record<string, unknown>;
  results: CTOutputs | PTOutputs | null;
  predictions: Record<string, number> | null;
}

export function PrintButton({ type, inputs, results, predictions }: PrintButtonProps) {
  function handlePrint() {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    const resultsHTML = results
      ? Object.entries(results)
          .map(([key, val]) => {
            if (typeof val === "object" && val !== null) {
              return `<tr><td>${key}</td><td>${Object.entries(val as Record<string, number>)
                .map(([k, v]) => `${k}: ${v}`)
                .join(", ")}</td></tr>`;
            }
            return `<tr><td>${key}</td><td>${val}</td></tr>`;
          })
          .join("")
      : "";

    const predictionsHTML = predictions
      ? Object.entries(predictions)
          .map(([key, val]) => `<tr><td>${key}</td><td>${val.toFixed(4)}</td></tr>`)
          .join("")
      : "";

    const inputsHTML = Object.entries(inputs)
      .map(([key, val]) => `<tr><td>${key}</td><td>${val}</td></tr>`)
      .join("");

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>TransformerGO — ${type} Results</title>
        <style>
          body { font-family: Arial, sans-serif; padding: 30px; color: #000; }
          h1 { font-size: 24px; margin-bottom: 4px; }
          h2 { font-size: 16px; margin-top: 24px; margin-bottom: 8px; border-bottom: 1px solid #ccc; padding-bottom: 4px; }
          .subtitle { color: #666; font-size: 13px; margin-bottom: 24px; }
          table { width: 100%; border-collapse: collapse; margin-bottom: 16px; }
          td { padding: 6px 10px; border: 1px solid #ddd; font-size: 13px; }
          td:first-child { font-weight: bold; width: 50%; background: #f5f5f5; }
          .footer { margin-top: 40px; font-size: 11px; color: #999; text-align: center; }
        </style>
      </head>
      <body>
        <h1>TransformerGO</h1>
        <p class="subtitle">${type === "CT" ? "Current Transformer" : "Potential Transformer"} — Design Report</p>
        <p class="subtitle">Generated: ${new Date().toLocaleString()}</p>

        <h2>Input Parameters</h2>
        <table>${inputsHTML}</table>

        ${results ? `<h2>Computed Results</h2><table>${resultsHTML}</table>` : ""}
        ${predictions ? `<h2>ML Error Predictions</h2><table>${predictionsHTML}</table>` : ""}

        <div class="footer">Generated by TransformerGO — Electrical Engineering Tool</div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  }

  return (
    <button
      onClick={handlePrint}
      disabled={!results}
      className="w-full py-3 rounded-lg font-orbitron font-semibold tracking-wider text-sm transition-all duration-300 border border-[#1e3a5f] text-[#9ca3af] hover:border-[#00d4ff] hover:text-[#00d4ff] disabled:opacity-30 disabled:cursor-not-allowed flex items-center justify-center gap-2"
    >
      🖨️ Export / Print Report
    </button>
  );
}